export default {
  initialColorMode: 'dark',
  link: 'tomato',
  text: '#FFFAFA',
  textSecondary: '#666',
  textError: '#cf1b0e',
  background: '#1b262c',
  backgroundSecondary: '#bbe1fa',
  colorOne: '#1b262c',
  colorTwo: '#0f4c75',
  colorThree: '#3282b8',
  colorFour: '#bbe1fa',
  offWhite: '#e1e1e1',
  white: '#fff',
  modes: {
    light: {
      link: 'tomato',
      text: '#666',
      textSecondary: '#FFFAFA',
      textError: '#cf1b0e',
      background: '#3e64ff',
      backgroundSecondary: '#3e64ff',
      colorOne: '#ecfcff',
      colorTwo: '#b2fcff',
      colorThree: '#5edfff',
      colorFour: '#3e64ff',
      offWhite: '#e1e1e1',
      white: '#fff',
    },
  },
}
