export default {
  initialColorMode: 'dark',
  link: 'tomato',
  text: '#fffafa',
  textSecondary: '#666',
  textError: '#cf1b0e',
  background: '#222831',
  backgroundSecondary: '#393e46',
  colorOne: '#222831',
  colorTwo: '#393e46',
  colorThree: '#b55400',
  colorFour: '#eeeeee',
  offWhite: '#e1e1e1',
  white: '#fff',
  modes: {
    light: {
      link: 'tomato',
      text: '#666',
      textSecondary: '#666',
      textError: '#cf1b0e',
      background: '#b1bed5',
      backgroundSecondary: '#bfd8d5',
      colorOne: '#b1bed5',
      colorTwo: '#bfd8d5',
      colorThree: '#dfdfdf',
      colorFour: '#f4f3f3',

      white: '#fff',
    },
  },
}
