export default {
  initialColorMode: 'dark',
  link: 'tomato',
  text: '#FFFAFA',
  textSecondary: '#666',
  textError: '#cf1b0e',
  background: '#1b262c',
  backgroundSecondary: '#bbe1fa',
  colorOne: '#1b262c',
  colorTwo: '#0f4c75',
  colorThree: '#3282b8',
  colorFour: '#bbe1fa',
  offWhite: '#e1e1e1',
  white: '#fff',
  modes: {
    light: {
      link: 'tomato',
      text: '#666',
      textSecondary: '#666',
      textError: '#cf1b0e',
      background: '#e0ece4',
      backgroundSecondary: '#f7f2e7',
      colorOne: '#e0ece4',
      colorTwo: '#f7f2e7',
      colorThree: '#d8d3cd',
      colorFour: '#d8d3cd',
      offWhite: '#e1e1e1',
      white: '#fff',
    },
  },
}
